- name: make an service
  template:
    src: "cmd.service.j2"
    dest: "/etc/systemd/system/{{ name }}.service"
  become: true

- name: start
  systemd:
    name: "{{ name }}"
    daemon_reload: yes
    state: restarted
    enabled: yes
  become: true
