- name: mkdir
  file:
    path: "~/.config/systemd/user/"
    state: directory

- name: mkdir
  file:
    path: "{{path}}"
    state: directory

- name: fix target
  set_fact:
    target: "default.target"

- name: make an service
  template:
    src: "cmd.service.j2"
    dest: "~/.config/systemd/user/{{ name }}.service"

- name: start
  systemd:
    name: "{{ name }}"
    daemon_reload: yes
    state: restarted
    enabled: yes
    scope: user
